// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cli_def/chat.proto

package protobuf.generate.cli2srv.chat;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CPrivateChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CPrivateChat)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *发送消息者的userid
     * </pre>
     *
     * <code>required string self = 1;</code>
     */
    boolean hasSelf();
    /**
     * <pre>
     *发送消息者的userid
     * </pre>
     *
     * <code>required string self = 1;</code>
     */
    java.lang.String getSelf();
    /**
     * <pre>
     *发送消息者的userid
     * </pre>
     *
     * <code>required string self = 1;</code>
     */
    com.google.protobuf.ByteString
        getSelfBytes();

    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>required string dest = 2;</code>
     */
    boolean hasDest();
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>required string dest = 2;</code>
     */
    java.lang.String getDest();
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>required string dest = 2;</code>
     */
    com.google.protobuf.ByteString
        getDestBytes();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 3;</code>
     */
    boolean hasContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code CPrivateChat}
   */
  public  static final class CPrivateChat extends
      com.google.protobuf.GeneratedMessageLite<
          CPrivateChat, CPrivateChat.Builder> implements
      // @@protoc_insertion_point(message_implements:CPrivateChat)
      CPrivateChatOrBuilder {
    private CPrivateChat() {
      self_ = "";
      dest_ = "";
      content_ = "";
    }
    private int bitField0_;
    public static final int SELF_FIELD_NUMBER = 1;
    private java.lang.String self_;
    /**
     * <pre>
     *发送消息者的userid
     * </pre>
     *
     * <code>required string self = 1;</code>
     */
    public boolean hasSelf() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *发送消息者的userid
     * </pre>
     *
     * <code>required string self = 1;</code>
     */
    public java.lang.String getSelf() {
      return self_;
    }
    /**
     * <pre>
     *发送消息者的userid
     * </pre>
     *
     * <code>required string self = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSelfBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(self_);
    }
    /**
     * <pre>
     *发送消息者的userid
     * </pre>
     *
     * <code>required string self = 1;</code>
     */
    private void setSelf(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      self_ = value;
    }
    /**
     * <pre>
     *发送消息者的userid
     * </pre>
     *
     * <code>required string self = 1;</code>
     */
    private void clearSelf() {
      bitField0_ = (bitField0_ & ~0x00000001);
      self_ = getDefaultInstance().getSelf();
    }
    /**
     * <pre>
     *发送消息者的userid
     * </pre>
     *
     * <code>required string self = 1;</code>
     */
    private void setSelfBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      self_ = value.toStringUtf8();
    }

    public static final int DEST_FIELD_NUMBER = 2;
    private java.lang.String dest_;
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>required string dest = 2;</code>
     */
    public boolean hasDest() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>required string dest = 2;</code>
     */
    public java.lang.String getDest() {
      return dest_;
    }
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>required string dest = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDestBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(dest_);
    }
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>required string dest = 2;</code>
     */
    private void setDest(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      dest_ = value;
    }
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>required string dest = 2;</code>
     */
    private void clearDest() {
      bitField0_ = (bitField0_ & ~0x00000002);
      dest_ = getDefaultInstance().getDest();
    }
    /**
     * <pre>
     *消息目标的userid
     * </pre>
     *
     * <code>required string dest = 2;</code>
     */
    private void setDestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      dest_ = value.toStringUtf8();
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private java.lang.String content_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 3;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 3;</code>
     */
    public java.lang.String getContent() {
      return content_;
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(content_);
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 3;</code>
     */
    private void setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      content_ = value;
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 3;</code>
     */
    private void clearContent() {
      bitField0_ = (bitField0_ & ~0x00000004);
      content_ = getDefaultInstance().getContent();
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>required string content = 3;</code>
     */
    private void setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      content_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getSelf());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getDest());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeString(3, getContent());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSelf());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getDest());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getContent());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static protobuf.generate.cli2srv.chat.Chat.CPrivateChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static protobuf.generate.cli2srv.chat.Chat.CPrivateChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.chat.Chat.CPrivateChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static protobuf.generate.cli2srv.chat.Chat.CPrivateChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.chat.Chat.CPrivateChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.chat.Chat.CPrivateChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.chat.Chat.CPrivateChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.chat.Chat.CPrivateChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.chat.Chat.CPrivateChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.chat.Chat.CPrivateChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.generate.cli2srv.chat.Chat.CPrivateChat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code CPrivateChat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          protobuf.generate.cli2srv.chat.Chat.CPrivateChat, Builder> implements
        // @@protoc_insertion_point(builder_implements:CPrivateChat)
        protobuf.generate.cli2srv.chat.Chat.CPrivateChatOrBuilder {
      // Construct using protobuf.generate.cli2srv.chat.Chat.CPrivateChat.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *发送消息者的userid
       * </pre>
       *
       * <code>required string self = 1;</code>
       */
      public boolean hasSelf() {
        return instance.hasSelf();
      }
      /**
       * <pre>
       *发送消息者的userid
       * </pre>
       *
       * <code>required string self = 1;</code>
       */
      public java.lang.String getSelf() {
        return instance.getSelf();
      }
      /**
       * <pre>
       *发送消息者的userid
       * </pre>
       *
       * <code>required string self = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSelfBytes() {
        return instance.getSelfBytes();
      }
      /**
       * <pre>
       *发送消息者的userid
       * </pre>
       *
       * <code>required string self = 1;</code>
       */
      public Builder setSelf(
          java.lang.String value) {
        copyOnWrite();
        instance.setSelf(value);
        return this;
      }
      /**
       * <pre>
       *发送消息者的userid
       * </pre>
       *
       * <code>required string self = 1;</code>
       */
      public Builder clearSelf() {
        copyOnWrite();
        instance.clearSelf();
        return this;
      }
      /**
       * <pre>
       *发送消息者的userid
       * </pre>
       *
       * <code>required string self = 1;</code>
       */
      public Builder setSelfBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSelfBytes(value);
        return this;
      }

      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>required string dest = 2;</code>
       */
      public boolean hasDest() {
        return instance.hasDest();
      }
      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>required string dest = 2;</code>
       */
      public java.lang.String getDest() {
        return instance.getDest();
      }
      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>required string dest = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDestBytes() {
        return instance.getDestBytes();
      }
      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>required string dest = 2;</code>
       */
      public Builder setDest(
          java.lang.String value) {
        copyOnWrite();
        instance.setDest(value);
        return this;
      }
      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>required string dest = 2;</code>
       */
      public Builder clearDest() {
        copyOnWrite();
        instance.clearDest();
        return this;
      }
      /**
       * <pre>
       *消息目标的userid
       * </pre>
       *
       * <code>required string dest = 2;</code>
       */
      public Builder setDestBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDestBytes(value);
        return this;
      }

      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required string content = 3;</code>
       */
      public boolean hasContent() {
        return instance.hasContent();
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required string content = 3;</code>
       */
      public java.lang.String getContent() {
        return instance.getContent();
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        return instance.getContentBytes();
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required string content = 3;</code>
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>required string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContentBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CPrivateChat)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new protobuf.generate.cli2srv.chat.Chat.CPrivateChat();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasSelf()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasDest()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasContent()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          protobuf.generate.cli2srv.chat.Chat.CPrivateChat other = (protobuf.generate.cli2srv.chat.Chat.CPrivateChat) arg1;
          self_ = visitor.visitString(
              hasSelf(), self_,
              other.hasSelf(), other.self_);
          dest_ = visitor.visitString(
              hasDest(), dest_,
              other.hasDest(), other.dest_);
          content_ = visitor.visitString(
              hasContent(), content_,
              other.hasContent(), other.content_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readString();
                  bitField0_ |= 0x00000001;
                  self_ = s;
                  break;
                }
                case 18: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  dest_ = s;
                  break;
                }
                case 26: {
                  String s = input.readString();
                  bitField0_ |= 0x00000004;
                  content_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (protobuf.generate.cli2srv.chat.Chat.CPrivateChat.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:CPrivateChat)
    private static final protobuf.generate.cli2srv.chat.Chat.CPrivateChat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CPrivateChat();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static protobuf.generate.cli2srv.chat.Chat.CPrivateChat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CPrivateChat> PARSER;

    public static com.google.protobuf.Parser<CPrivateChat> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SPrivateChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SPrivateChat)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string content = 1;</code>
     */
    boolean hasContent();
    /**
     * <code>required string content = 1;</code>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 1;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code SPrivateChat}
   */
  public  static final class SPrivateChat extends
      com.google.protobuf.GeneratedMessageLite<
          SPrivateChat, SPrivateChat.Builder> implements
      // @@protoc_insertion_point(message_implements:SPrivateChat)
      SPrivateChatOrBuilder {
    private SPrivateChat() {
      content_ = "";
    }
    private int bitField0_;
    public static final int CONTENT_FIELD_NUMBER = 1;
    private java.lang.String content_;
    /**
     * <code>required string content = 1;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string content = 1;</code>
     */
    public java.lang.String getContent() {
      return content_;
    }
    /**
     * <code>required string content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(content_);
    }
    /**
     * <code>required string content = 1;</code>
     */
    private void setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      content_ = value;
    }
    /**
     * <code>required string content = 1;</code>
     */
    private void clearContent() {
      bitField0_ = (bitField0_ & ~0x00000001);
      content_ = getDefaultInstance().getContent();
    }
    /**
     * <code>required string content = 1;</code>
     */
    private void setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      content_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getContent());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getContent());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static protobuf.generate.cli2srv.chat.Chat.SPrivateChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static protobuf.generate.cli2srv.chat.Chat.SPrivateChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.chat.Chat.SPrivateChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static protobuf.generate.cli2srv.chat.Chat.SPrivateChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.chat.Chat.SPrivateChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.chat.Chat.SPrivateChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.chat.Chat.SPrivateChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.chat.Chat.SPrivateChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.chat.Chat.SPrivateChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.chat.Chat.SPrivateChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.generate.cli2srv.chat.Chat.SPrivateChat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code SPrivateChat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          protobuf.generate.cli2srv.chat.Chat.SPrivateChat, Builder> implements
        // @@protoc_insertion_point(builder_implements:SPrivateChat)
        protobuf.generate.cli2srv.chat.Chat.SPrivateChatOrBuilder {
      // Construct using protobuf.generate.cli2srv.chat.Chat.SPrivateChat.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required string content = 1;</code>
       */
      public boolean hasContent() {
        return instance.hasContent();
      }
      /**
       * <code>required string content = 1;</code>
       */
      public java.lang.String getContent() {
        return instance.getContent();
      }
      /**
       * <code>required string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        return instance.getContentBytes();
      }
      /**
       * <code>required string content = 1;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <code>required string content = 1;</code>
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }
      /**
       * <code>required string content = 1;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContentBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SPrivateChat)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new protobuf.generate.cli2srv.chat.Chat.SPrivateChat();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasContent()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          protobuf.generate.cli2srv.chat.Chat.SPrivateChat other = (protobuf.generate.cli2srv.chat.Chat.SPrivateChat) arg1;
          content_ = visitor.visitString(
              hasContent(), content_,
              other.hasContent(), other.content_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readString();
                  bitField0_ |= 0x00000001;
                  content_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (protobuf.generate.cli2srv.chat.Chat.SPrivateChat.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SPrivateChat)
    private static final protobuf.generate.cli2srv.chat.Chat.SPrivateChat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SPrivateChat();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static protobuf.generate.cli2srv.chat.Chat.SPrivateChat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SPrivateChat> PARSER;

    public static com.google.protobuf.Parser<SPrivateChat> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
