// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cli_def/login.proto

package protobuf.generate.cli2srv.login;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CRegisterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CRegister)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string userid = 1;</code>
     */
    boolean hasUserid();
    /**
     * <code>required string userid = 1;</code>
     */
    java.lang.String getUserid();
    /**
     * <code>required string userid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUseridBytes();

    /**
     * <code>required string passwd = 2;</code>
     */
    boolean hasPasswd();
    /**
     * <code>required string passwd = 2;</code>
     */
    java.lang.String getPasswd();
    /**
     * <code>required string passwd = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswdBytes();
  }
  /**
   * Protobuf type {@code CRegister}
   */
  public  static final class CRegister extends
      com.google.protobuf.GeneratedMessageLite<
          CRegister, CRegister.Builder> implements
      // @@protoc_insertion_point(message_implements:CRegister)
      CRegisterOrBuilder {
    private CRegister() {
      userid_ = "";
      passwd_ = "";
    }
    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.String userid_;
    /**
     * <code>required string userid = 1;</code>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string userid = 1;</code>
     */
    public java.lang.String getUserid() {
      return userid_;
    }
    /**
     * <code>required string userid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUseridBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userid_);
    }
    /**
     * <code>required string userid = 1;</code>
     */
    private void setUserid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userid_ = value;
    }
    /**
     * <code>required string userid = 1;</code>
     */
    private void clearUserid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userid_ = getDefaultInstance().getUserid();
    }
    /**
     * <code>required string userid = 1;</code>
     */
    private void setUseridBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userid_ = value.toStringUtf8();
    }

    public static final int PASSWD_FIELD_NUMBER = 2;
    private java.lang.String passwd_;
    /**
     * <code>required string passwd = 2;</code>
     */
    public boolean hasPasswd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string passwd = 2;</code>
     */
    public java.lang.String getPasswd() {
      return passwd_;
    }
    /**
     * <code>required string passwd = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(passwd_);
    }
    /**
     * <code>required string passwd = 2;</code>
     */
    private void setPasswd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      passwd_ = value;
    }
    /**
     * <code>required string passwd = 2;</code>
     */
    private void clearPasswd() {
      bitField0_ = (bitField0_ & ~0x00000002);
      passwd_ = getDefaultInstance().getPasswd();
    }
    /**
     * <code>required string passwd = 2;</code>
     */
    private void setPasswdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      passwd_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getUserid());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getPasswd());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUserid());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPasswd());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static protobuf.generate.cli2srv.login.Auth.CRegister parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static protobuf.generate.cli2srv.login.Auth.CRegister parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.CRegister parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static protobuf.generate.cli2srv.login.Auth.CRegister parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.CRegister parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.login.Auth.CRegister parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.CRegister parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.login.Auth.CRegister parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.CRegister parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.login.Auth.CRegister parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.generate.cli2srv.login.Auth.CRegister prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code CRegister}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          protobuf.generate.cli2srv.login.Auth.CRegister, Builder> implements
        // @@protoc_insertion_point(builder_implements:CRegister)
        protobuf.generate.cli2srv.login.Auth.CRegisterOrBuilder {
      // Construct using protobuf.generate.cli2srv.login.Auth.CRegister.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required string userid = 1;</code>
       */
      public boolean hasUserid() {
        return instance.hasUserid();
      }
      /**
       * <code>required string userid = 1;</code>
       */
      public java.lang.String getUserid() {
        return instance.getUserid();
      }
      /**
       * <code>required string userid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUseridBytes() {
        return instance.getUseridBytes();
      }
      /**
       * <code>required string userid = 1;</code>
       */
      public Builder setUserid(
          java.lang.String value) {
        copyOnWrite();
        instance.setUserid(value);
        return this;
      }
      /**
       * <code>required string userid = 1;</code>
       */
      public Builder clearUserid() {
        copyOnWrite();
        instance.clearUserid();
        return this;
      }
      /**
       * <code>required string userid = 1;</code>
       */
      public Builder setUseridBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUseridBytes(value);
        return this;
      }

      /**
       * <code>required string passwd = 2;</code>
       */
      public boolean hasPasswd() {
        return instance.hasPasswd();
      }
      /**
       * <code>required string passwd = 2;</code>
       */
      public java.lang.String getPasswd() {
        return instance.getPasswd();
      }
      /**
       * <code>required string passwd = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswdBytes() {
        return instance.getPasswdBytes();
      }
      /**
       * <code>required string passwd = 2;</code>
       */
      public Builder setPasswd(
          java.lang.String value) {
        copyOnWrite();
        instance.setPasswd(value);
        return this;
      }
      /**
       * <code>required string passwd = 2;</code>
       */
      public Builder clearPasswd() {
        copyOnWrite();
        instance.clearPasswd();
        return this;
      }
      /**
       * <code>required string passwd = 2;</code>
       */
      public Builder setPasswdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPasswdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CRegister)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new protobuf.generate.cli2srv.login.Auth.CRegister();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasUserid()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasPasswd()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          protobuf.generate.cli2srv.login.Auth.CRegister other = (protobuf.generate.cli2srv.login.Auth.CRegister) arg1;
          userid_ = visitor.visitString(
              hasUserid(), userid_,
              other.hasUserid(), other.userid_);
          passwd_ = visitor.visitString(
              hasPasswd(), passwd_,
              other.hasPasswd(), other.passwd_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readString();
                  bitField0_ |= 0x00000001;
                  userid_ = s;
                  break;
                }
                case 18: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  passwd_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (protobuf.generate.cli2srv.login.Auth.CRegister.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:CRegister)
    private static final protobuf.generate.cli2srv.login.Auth.CRegister DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CRegister();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static protobuf.generate.cli2srv.login.Auth.CRegister getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CRegister> PARSER;

    public static com.google.protobuf.Parser<CRegister> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CLogin)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 用户账户id
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    boolean hasUserid();
    /**
     * <pre>
     * 用户账户id
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    java.lang.String getUserid();
    /**
     * <pre>
     * 用户账户id
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUseridBytes();

    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>required string passwd = 2;</code>
     */
    boolean hasPasswd();
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>required string passwd = 2;</code>
     */
    java.lang.String getPasswd();
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>required string passwd = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswdBytes();

    /**
     * <pre>
     * 客户端平台:android,ios,web
     * </pre>
     *
     * <code>optional string platform = 3;</code>
     */
    boolean hasPlatform();
    /**
     * <pre>
     * 客户端平台:android,ios,web
     * </pre>
     *
     * <code>optional string platform = 3;</code>
     */
    java.lang.String getPlatform();
    /**
     * <pre>
     * 客户端平台:android,ios,web
     * </pre>
     *
     * <code>optional string platform = 3;</code>
     */
    com.google.protobuf.ByteString
        getPlatformBytes();

    /**
     * <pre>
     * APP版本号
     * </pre>
     *
     * <code>optional string app_version = 4;</code>
     */
    boolean hasAppVersion();
    /**
     * <pre>
     * APP版本号
     * </pre>
     *
     * <code>optional string app_version = 4;</code>
     */
    java.lang.String getAppVersion();
    /**
     * <pre>
     * APP版本号
     * </pre>
     *
     * <code>optional string app_version = 4;</code>
     */
    com.google.protobuf.ByteString
        getAppVersionBytes();
  }
  /**
   * Protobuf type {@code CLogin}
   */
  public  static final class CLogin extends
      com.google.protobuf.GeneratedMessageLite<
          CLogin, CLogin.Builder> implements
      // @@protoc_insertion_point(message_implements:CLogin)
      CLoginOrBuilder {
    private CLogin() {
      userid_ = "";
      passwd_ = "";
      platform_ = "";
      appVersion_ = "";
    }
    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.lang.String userid_;
    /**
     * <pre>
     * 用户账户id
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * 用户账户id
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    public java.lang.String getUserid() {
      return userid_;
    }
    /**
     * <pre>
     * 用户账户id
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUseridBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userid_);
    }
    /**
     * <pre>
     * 用户账户id
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    private void setUserid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userid_ = value;
    }
    /**
     * <pre>
     * 用户账户id
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    private void clearUserid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userid_ = getDefaultInstance().getUserid();
    }
    /**
     * <pre>
     * 用户账户id
     * </pre>
     *
     * <code>required string userid = 1;</code>
     */
    private void setUseridBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userid_ = value.toStringUtf8();
    }

    public static final int PASSWD_FIELD_NUMBER = 2;
    private java.lang.String passwd_;
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>required string passwd = 2;</code>
     */
    public boolean hasPasswd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>required string passwd = 2;</code>
     */
    public java.lang.String getPasswd() {
      return passwd_;
    }
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>required string passwd = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(passwd_);
    }
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>required string passwd = 2;</code>
     */
    private void setPasswd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      passwd_ = value;
    }
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>required string passwd = 2;</code>
     */
    private void clearPasswd() {
      bitField0_ = (bitField0_ & ~0x00000002);
      passwd_ = getDefaultInstance().getPasswd();
    }
    /**
     * <pre>
     * 用户密码
     * </pre>
     *
     * <code>required string passwd = 2;</code>
     */
    private void setPasswdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      passwd_ = value.toStringUtf8();
    }

    public static final int PLATFORM_FIELD_NUMBER = 3;
    private java.lang.String platform_;
    /**
     * <pre>
     * 客户端平台:android,ios,web
     * </pre>
     *
     * <code>optional string platform = 3;</code>
     */
    public boolean hasPlatform() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 客户端平台:android,ios,web
     * </pre>
     *
     * <code>optional string platform = 3;</code>
     */
    public java.lang.String getPlatform() {
      return platform_;
    }
    /**
     * <pre>
     * 客户端平台:android,ios,web
     * </pre>
     *
     * <code>optional string platform = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(platform_);
    }
    /**
     * <pre>
     * 客户端平台:android,ios,web
     * </pre>
     *
     * <code>optional string platform = 3;</code>
     */
    private void setPlatform(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      platform_ = value;
    }
    /**
     * <pre>
     * 客户端平台:android,ios,web
     * </pre>
     *
     * <code>optional string platform = 3;</code>
     */
    private void clearPlatform() {
      bitField0_ = (bitField0_ & ~0x00000004);
      platform_ = getDefaultInstance().getPlatform();
    }
    /**
     * <pre>
     * 客户端平台:android,ios,web
     * </pre>
     *
     * <code>optional string platform = 3;</code>
     */
    private void setPlatformBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      platform_ = value.toStringUtf8();
    }

    public static final int APP_VERSION_FIELD_NUMBER = 4;
    private java.lang.String appVersion_;
    /**
     * <pre>
     * APP版本号
     * </pre>
     *
     * <code>optional string app_version = 4;</code>
     */
    public boolean hasAppVersion() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * APP版本号
     * </pre>
     *
     * <code>optional string app_version = 4;</code>
     */
    public java.lang.String getAppVersion() {
      return appVersion_;
    }
    /**
     * <pre>
     * APP版本号
     * </pre>
     *
     * <code>optional string app_version = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(appVersion_);
    }
    /**
     * <pre>
     * APP版本号
     * </pre>
     *
     * <code>optional string app_version = 4;</code>
     */
    private void setAppVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      appVersion_ = value;
    }
    /**
     * <pre>
     * APP版本号
     * </pre>
     *
     * <code>optional string app_version = 4;</code>
     */
    private void clearAppVersion() {
      bitField0_ = (bitField0_ & ~0x00000008);
      appVersion_ = getDefaultInstance().getAppVersion();
    }
    /**
     * <pre>
     * APP版本号
     * </pre>
     *
     * <code>optional string app_version = 4;</code>
     */
    private void setAppVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      appVersion_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getUserid());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getPasswd());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeString(3, getPlatform());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeString(4, getAppVersion());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUserid());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPasswd());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getPlatform());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getAppVersion());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.login.Auth.CLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.generate.cli2srv.login.Auth.CLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code CLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          protobuf.generate.cli2srv.login.Auth.CLogin, Builder> implements
        // @@protoc_insertion_point(builder_implements:CLogin)
        protobuf.generate.cli2srv.login.Auth.CLoginOrBuilder {
      // Construct using protobuf.generate.cli2srv.login.Auth.CLogin.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 用户账户id
       * </pre>
       *
       * <code>required string userid = 1;</code>
       */
      public boolean hasUserid() {
        return instance.hasUserid();
      }
      /**
       * <pre>
       * 用户账户id
       * </pre>
       *
       * <code>required string userid = 1;</code>
       */
      public java.lang.String getUserid() {
        return instance.getUserid();
      }
      /**
       * <pre>
       * 用户账户id
       * </pre>
       *
       * <code>required string userid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUseridBytes() {
        return instance.getUseridBytes();
      }
      /**
       * <pre>
       * 用户账户id
       * </pre>
       *
       * <code>required string userid = 1;</code>
       */
      public Builder setUserid(
          java.lang.String value) {
        copyOnWrite();
        instance.setUserid(value);
        return this;
      }
      /**
       * <pre>
       * 用户账户id
       * </pre>
       *
       * <code>required string userid = 1;</code>
       */
      public Builder clearUserid() {
        copyOnWrite();
        instance.clearUserid();
        return this;
      }
      /**
       * <pre>
       * 用户账户id
       * </pre>
       *
       * <code>required string userid = 1;</code>
       */
      public Builder setUseridBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUseridBytes(value);
        return this;
      }

      /**
       * <pre>
       * 用户密码
       * </pre>
       *
       * <code>required string passwd = 2;</code>
       */
      public boolean hasPasswd() {
        return instance.hasPasswd();
      }
      /**
       * <pre>
       * 用户密码
       * </pre>
       *
       * <code>required string passwd = 2;</code>
       */
      public java.lang.String getPasswd() {
        return instance.getPasswd();
      }
      /**
       * <pre>
       * 用户密码
       * </pre>
       *
       * <code>required string passwd = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswdBytes() {
        return instance.getPasswdBytes();
      }
      /**
       * <pre>
       * 用户密码
       * </pre>
       *
       * <code>required string passwd = 2;</code>
       */
      public Builder setPasswd(
          java.lang.String value) {
        copyOnWrite();
        instance.setPasswd(value);
        return this;
      }
      /**
       * <pre>
       * 用户密码
       * </pre>
       *
       * <code>required string passwd = 2;</code>
       */
      public Builder clearPasswd() {
        copyOnWrite();
        instance.clearPasswd();
        return this;
      }
      /**
       * <pre>
       * 用户密码
       * </pre>
       *
       * <code>required string passwd = 2;</code>
       */
      public Builder setPasswdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPasswdBytes(value);
        return this;
      }

      /**
       * <pre>
       * 客户端平台:android,ios,web
       * </pre>
       *
       * <code>optional string platform = 3;</code>
       */
      public boolean hasPlatform() {
        return instance.hasPlatform();
      }
      /**
       * <pre>
       * 客户端平台:android,ios,web
       * </pre>
       *
       * <code>optional string platform = 3;</code>
       */
      public java.lang.String getPlatform() {
        return instance.getPlatform();
      }
      /**
       * <pre>
       * 客户端平台:android,ios,web
       * </pre>
       *
       * <code>optional string platform = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformBytes() {
        return instance.getPlatformBytes();
      }
      /**
       * <pre>
       * 客户端平台:android,ios,web
       * </pre>
       *
       * <code>optional string platform = 3;</code>
       */
      public Builder setPlatform(
          java.lang.String value) {
        copyOnWrite();
        instance.setPlatform(value);
        return this;
      }
      /**
       * <pre>
       * 客户端平台:android,ios,web
       * </pre>
       *
       * <code>optional string platform = 3;</code>
       */
      public Builder clearPlatform() {
        copyOnWrite();
        instance.clearPlatform();
        return this;
      }
      /**
       * <pre>
       * 客户端平台:android,ios,web
       * </pre>
       *
       * <code>optional string platform = 3;</code>
       */
      public Builder setPlatformBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPlatformBytes(value);
        return this;
      }

      /**
       * <pre>
       * APP版本号
       * </pre>
       *
       * <code>optional string app_version = 4;</code>
       */
      public boolean hasAppVersion() {
        return instance.hasAppVersion();
      }
      /**
       * <pre>
       * APP版本号
       * </pre>
       *
       * <code>optional string app_version = 4;</code>
       */
      public java.lang.String getAppVersion() {
        return instance.getAppVersion();
      }
      /**
       * <pre>
       * APP版本号
       * </pre>
       *
       * <code>optional string app_version = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAppVersionBytes() {
        return instance.getAppVersionBytes();
      }
      /**
       * <pre>
       * APP版本号
       * </pre>
       *
       * <code>optional string app_version = 4;</code>
       */
      public Builder setAppVersion(
          java.lang.String value) {
        copyOnWrite();
        instance.setAppVersion(value);
        return this;
      }
      /**
       * <pre>
       * APP版本号
       * </pre>
       *
       * <code>optional string app_version = 4;</code>
       */
      public Builder clearAppVersion() {
        copyOnWrite();
        instance.clearAppVersion();
        return this;
      }
      /**
       * <pre>
       * APP版本号
       * </pre>
       *
       * <code>optional string app_version = 4;</code>
       */
      public Builder setAppVersionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAppVersionBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CLogin)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new protobuf.generate.cli2srv.login.Auth.CLogin();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasUserid()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasPasswd()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          protobuf.generate.cli2srv.login.Auth.CLogin other = (protobuf.generate.cli2srv.login.Auth.CLogin) arg1;
          userid_ = visitor.visitString(
              hasUserid(), userid_,
              other.hasUserid(), other.userid_);
          passwd_ = visitor.visitString(
              hasPasswd(), passwd_,
              other.hasPasswd(), other.passwd_);
          platform_ = visitor.visitString(
              hasPlatform(), platform_,
              other.hasPlatform(), other.platform_);
          appVersion_ = visitor.visitString(
              hasAppVersion(), appVersion_,
              other.hasAppVersion(), other.appVersion_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readString();
                  bitField0_ |= 0x00000001;
                  userid_ = s;
                  break;
                }
                case 18: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  passwd_ = s;
                  break;
                }
                case 26: {
                  String s = input.readString();
                  bitField0_ |= 0x00000004;
                  platform_ = s;
                  break;
                }
                case 34: {
                  String s = input.readString();
                  bitField0_ |= 0x00000008;
                  appVersion_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (protobuf.generate.cli2srv.login.Auth.CLogin.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:CLogin)
    private static final protobuf.generate.cli2srv.login.Auth.CLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CLogin();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static protobuf.generate.cli2srv.login.Auth.CLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CLogin> PARSER;

    public static com.google.protobuf.Parser<CLogin> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *返回码
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    boolean hasCode();
    /**
     * <pre>
     *返回码
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    int getCode();

    /**
     * <pre>
     *描述
     * </pre>
     *
     * <code>required string desc = 2;</code>
     */
    boolean hasDesc();
    /**
     * <pre>
     *描述
     * </pre>
     *
     * <code>required string desc = 2;</code>
     */
    java.lang.String getDesc();
    /**
     * <pre>
     *描述
     * </pre>
     *
     * <code>required string desc = 2;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();
  }
  /**
   * <pre>
   *code：
   *200 -- ok
   *404 -- error
   *300 -- dumplicated registery
   * </pre>
   *
   * Protobuf type {@code SResponse}
   */
  public  static final class SResponse extends
      com.google.protobuf.GeneratedMessageLite<
          SResponse, SResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:SResponse)
      SResponseOrBuilder {
    private SResponse() {
      desc_ = "";
    }
    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     *返回码
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *返回码
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <pre>
     *返回码
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    private void setCode(int value) {
      bitField0_ |= 0x00000001;
      code_ = value;
    }
    /**
     * <pre>
     *返回码
     * </pre>
     *
     * <code>required int32 code = 1;</code>
     */
    private void clearCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      code_ = 0;
    }

    public static final int DESC_FIELD_NUMBER = 2;
    private java.lang.String desc_;
    /**
     * <pre>
     *描述
     * </pre>
     *
     * <code>required string desc = 2;</code>
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *描述
     * </pre>
     *
     * <code>required string desc = 2;</code>
     */
    public java.lang.String getDesc() {
      return desc_;
    }
    /**
     * <pre>
     *描述
     * </pre>
     *
     * <code>required string desc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(desc_);
    }
    /**
     * <pre>
     *描述
     * </pre>
     *
     * <code>required string desc = 2;</code>
     */
    private void setDesc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      desc_ = value;
    }
    /**
     * <pre>
     *描述
     * </pre>
     *
     * <code>required string desc = 2;</code>
     */
    private void clearDesc() {
      bitField0_ = (bitField0_ & ~0x00000002);
      desc_ = getDefaultInstance().getDesc();
    }
    /**
     * <pre>
     *描述
     * </pre>
     *
     * <code>required string desc = 2;</code>
     */
    private void setDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      desc_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(2, getDesc());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getDesc());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.cli2srv.login.Auth.SResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.generate.cli2srv.login.Auth.SResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *code：
     *200 -- ok
     *404 -- error
     *300 -- dumplicated registery
     * </pre>
     *
     * Protobuf type {@code SResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          protobuf.generate.cli2srv.login.Auth.SResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:SResponse)
        protobuf.generate.cli2srv.login.Auth.SResponseOrBuilder {
      // Construct using protobuf.generate.cli2srv.login.Auth.SResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *返回码
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public boolean hasCode() {
        return instance.hasCode();
      }
      /**
       * <pre>
       *返回码
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public int getCode() {
        return instance.getCode();
      }
      /**
       * <pre>
       *返回码
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        copyOnWrite();
        instance.setCode(value);
        return this;
      }
      /**
       * <pre>
       *返回码
       * </pre>
       *
       * <code>required int32 code = 1;</code>
       */
      public Builder clearCode() {
        copyOnWrite();
        instance.clearCode();
        return this;
      }

      /**
       * <pre>
       *描述
       * </pre>
       *
       * <code>required string desc = 2;</code>
       */
      public boolean hasDesc() {
        return instance.hasDesc();
      }
      /**
       * <pre>
       *描述
       * </pre>
       *
       * <code>required string desc = 2;</code>
       */
      public java.lang.String getDesc() {
        return instance.getDesc();
      }
      /**
       * <pre>
       *描述
       * </pre>
       *
       * <code>required string desc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        return instance.getDescBytes();
      }
      /**
       * <pre>
       *描述
       * </pre>
       *
       * <code>required string desc = 2;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        copyOnWrite();
        instance.setDesc(value);
        return this;
      }
      /**
       * <pre>
       *描述
       * </pre>
       *
       * <code>required string desc = 2;</code>
       */
      public Builder clearDesc() {
        copyOnWrite();
        instance.clearDesc();
        return this;
      }
      /**
       * <pre>
       *描述
       * </pre>
       *
       * <code>required string desc = 2;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDescBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SResponse)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new protobuf.generate.cli2srv.login.Auth.SResponse();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasCode()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasDesc()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          protobuf.generate.cli2srv.login.Auth.SResponse other = (protobuf.generate.cli2srv.login.Auth.SResponse) arg1;
          code_ = visitor.visitInt(
              hasCode(), code_,
              other.hasCode(), other.code_);
          desc_ = visitor.visitString(
              hasDesc(), desc_,
              other.hasDesc(), other.desc_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  code_ = input.readInt32();
                  break;
                }
                case 18: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  desc_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (protobuf.generate.cli2srv.login.Auth.SResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SResponse)
    private static final protobuf.generate.cli2srv.login.Auth.SResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static protobuf.generate.cli2srv.login.Auth.SResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SResponse> PARSER;

    public static com.google.protobuf.Parser<SResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
