// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal_def/internal.proto

package protobuf.generate.internal;

public final class Internal {
  private Internal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code Dest}
   */
  public enum Dest
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Client = 1;</code>
     */
    Client(1),
    /**
     * <code>Auth = 2;</code>
     */
    Auth(2),
    /**
     * <code>Logic = 3;</code>
     */
    Logic(3),
    /**
     * <code>Gate = 4;</code>
     */
    Gate(4),
    ;

    /**
     * <code>Client = 1;</code>
     */
    public static final int Client_VALUE = 1;
    /**
     * <code>Auth = 2;</code>
     */
    public static final int Auth_VALUE = 2;
    /**
     * <code>Logic = 3;</code>
     */
    public static final int Logic_VALUE = 3;
    /**
     * <code>Gate = 4;</code>
     */
    public static final int Gate_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Dest valueOf(int value) {
      return forNumber(value);
    }

    public static Dest forNumber(int value) {
      switch (value) {
        case 1: return Client;
        case 2: return Auth;
        case 3: return Logic;
        case 4: return Gate;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Dest>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Dest> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Dest>() {
            public Dest findValueByNumber(int number) {
              return Dest.forNumber(number);
            }
          };

    private final int value;

    private Dest(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Dest)
  }

  public interface GTransferOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GTransfer)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .Dest dest = 1;</code>
     */
    boolean hasDest();
    /**
     * <code>required .Dest dest = 1;</code>
     */
    protobuf.generate.internal.Internal.Dest getDest();

    /**
     * <code>optional uint64 netId = 2;</code>
     */
    boolean hasNetId();
    /**
     * <code>optional uint64 netId = 2;</code>
     */
    long getNetId();

    /**
     * <code>required string userId = 3;</code>
     */
    boolean hasUserId();
    /**
     * <code>required string userId = 3;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>required string userId = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>required uint32 ptoNum = 4;</code>
     */
    boolean hasPtoNum();
    /**
     * <code>required uint32 ptoNum = 4;</code>
     */
    int getPtoNum();

    /**
     * <code>required bytes msg = 5;</code>
     */
    boolean hasMsg();
    /**
     * <code>required bytes msg = 5;</code>
     */
    com.google.protobuf.ByteString getMsg();
  }
  /**
   * <pre>
   *服务间的中转协议
   * </pre>
   *
   * Protobuf type {@code GTransfer}
   */
  public  static final class GTransfer extends
      com.google.protobuf.GeneratedMessageLite<
          GTransfer, GTransfer.Builder> implements
      // @@protoc_insertion_point(message_implements:GTransfer)
      GTransferOrBuilder {
    private GTransfer() {
      dest_ = 1;
      userId_ = "";
      msg_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int DEST_FIELD_NUMBER = 1;
    private int dest_;
    /**
     * <code>required .Dest dest = 1;</code>
     */
    public boolean hasDest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Dest dest = 1;</code>
     */
    public protobuf.generate.internal.Internal.Dest getDest() {
      protobuf.generate.internal.Internal.Dest result = protobuf.generate.internal.Internal.Dest.forNumber(dest_);
      return result == null ? protobuf.generate.internal.Internal.Dest.Client : result;
    }
    /**
     * <code>required .Dest dest = 1;</code>
     */
    private void setDest(protobuf.generate.internal.Internal.Dest value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      dest_ = value.getNumber();
    }
    /**
     * <code>required .Dest dest = 1;</code>
     */
    private void clearDest() {
      bitField0_ = (bitField0_ & ~0x00000001);
      dest_ = 1;
    }

    public static final int NETID_FIELD_NUMBER = 2;
    private long netId_;
    /**
     * <code>optional uint64 netId = 2;</code>
     */
    public boolean hasNetId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 netId = 2;</code>
     */
    public long getNetId() {
      return netId_;
    }
    /**
     * <code>optional uint64 netId = 2;</code>
     */
    private void setNetId(long value) {
      bitField0_ |= 0x00000002;
      netId_ = value;
    }
    /**
     * <code>optional uint64 netId = 2;</code>
     */
    private void clearNetId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      netId_ = 0L;
    }

    public static final int USERID_FIELD_NUMBER = 3;
    private java.lang.String userId_;
    /**
     * <code>required string userId = 3;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string userId = 3;</code>
     */
    public java.lang.String getUserId() {
      return userId_;
    }
    /**
     * <code>required string userId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userId_);
    }
    /**
     * <code>required string userId = 3;</code>
     */
    private void setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      userId_ = value;
    }
    /**
     * <code>required string userId = 3;</code>
     */
    private void clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      userId_ = getDefaultInstance().getUserId();
    }
    /**
     * <code>required string userId = 3;</code>
     */
    private void setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      userId_ = value.toStringUtf8();
    }

    public static final int PTONUM_FIELD_NUMBER = 4;
    private int ptoNum_;
    /**
     * <code>required uint32 ptoNum = 4;</code>
     */
    public boolean hasPtoNum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 ptoNum = 4;</code>
     */
    public int getPtoNum() {
      return ptoNum_;
    }
    /**
     * <code>required uint32 ptoNum = 4;</code>
     */
    private void setPtoNum(int value) {
      bitField0_ |= 0x00000008;
      ptoNum_ = value;
    }
    /**
     * <code>required uint32 ptoNum = 4;</code>
     */
    private void clearPtoNum() {
      bitField0_ = (bitField0_ & ~0x00000008);
      ptoNum_ = 0;
    }

    public static final int MSG_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString msg_;
    /**
     * <code>required bytes msg = 5;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bytes msg = 5;</code>
     */
    public com.google.protobuf.ByteString getMsg() {
      return msg_;
    }
    /**
     * <code>required bytes msg = 5;</code>
     */
    private void setMsg(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      msg_ = value;
    }
    /**
     * <code>required bytes msg = 5;</code>
     */
    private void clearMsg() {
      bitField0_ = (bitField0_ & ~0x00000010);
      msg_ = getDefaultInstance().getMsg();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, dest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, netId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeString(3, getUserId());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, ptoNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, msg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, netId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getUserId());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, ptoNum_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static protobuf.generate.internal.Internal.GTransfer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static protobuf.generate.internal.Internal.GTransfer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static protobuf.generate.internal.Internal.GTransfer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static protobuf.generate.internal.Internal.GTransfer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static protobuf.generate.internal.Internal.GTransfer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.internal.Internal.GTransfer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static protobuf.generate.internal.Internal.GTransfer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.internal.Internal.GTransfer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static protobuf.generate.internal.Internal.GTransfer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.internal.Internal.GTransfer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.generate.internal.Internal.GTransfer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *服务间的中转协议
     * </pre>
     *
     * Protobuf type {@code GTransfer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          protobuf.generate.internal.Internal.GTransfer, Builder> implements
        // @@protoc_insertion_point(builder_implements:GTransfer)
        protobuf.generate.internal.Internal.GTransferOrBuilder {
      // Construct using protobuf.generate.internal.Internal.GTransfer.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required .Dest dest = 1;</code>
       */
      public boolean hasDest() {
        return instance.hasDest();
      }
      /**
       * <code>required .Dest dest = 1;</code>
       */
      public protobuf.generate.internal.Internal.Dest getDest() {
        return instance.getDest();
      }
      /**
       * <code>required .Dest dest = 1;</code>
       */
      public Builder setDest(protobuf.generate.internal.Internal.Dest value) {
        copyOnWrite();
        instance.setDest(value);
        return this;
      }
      /**
       * <code>required .Dest dest = 1;</code>
       */
      public Builder clearDest() {
        copyOnWrite();
        instance.clearDest();
        return this;
      }

      /**
       * <code>optional uint64 netId = 2;</code>
       */
      public boolean hasNetId() {
        return instance.hasNetId();
      }
      /**
       * <code>optional uint64 netId = 2;</code>
       */
      public long getNetId() {
        return instance.getNetId();
      }
      /**
       * <code>optional uint64 netId = 2;</code>
       */
      public Builder setNetId(long value) {
        copyOnWrite();
        instance.setNetId(value);
        return this;
      }
      /**
       * <code>optional uint64 netId = 2;</code>
       */
      public Builder clearNetId() {
        copyOnWrite();
        instance.clearNetId();
        return this;
      }

      /**
       * <code>required string userId = 3;</code>
       */
      public boolean hasUserId() {
        return instance.hasUserId();
      }
      /**
       * <code>required string userId = 3;</code>
       */
      public java.lang.String getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>required string userId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        return instance.getUserIdBytes();
      }
      /**
       * <code>required string userId = 3;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>required string userId = 3;</code>
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }
      /**
       * <code>required string userId = 3;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserIdBytes(value);
        return this;
      }

      /**
       * <code>required uint32 ptoNum = 4;</code>
       */
      public boolean hasPtoNum() {
        return instance.hasPtoNum();
      }
      /**
       * <code>required uint32 ptoNum = 4;</code>
       */
      public int getPtoNum() {
        return instance.getPtoNum();
      }
      /**
       * <code>required uint32 ptoNum = 4;</code>
       */
      public Builder setPtoNum(int value) {
        copyOnWrite();
        instance.setPtoNum(value);
        return this;
      }
      /**
       * <code>required uint32 ptoNum = 4;</code>
       */
      public Builder clearPtoNum() {
        copyOnWrite();
        instance.clearPtoNum();
        return this;
      }

      /**
       * <code>required bytes msg = 5;</code>
       */
      public boolean hasMsg() {
        return instance.hasMsg();
      }
      /**
       * <code>required bytes msg = 5;</code>
       */
      public com.google.protobuf.ByteString getMsg() {
        return instance.getMsg();
      }
      /**
       * <code>required bytes msg = 5;</code>
       */
      public Builder setMsg(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMsg(value);
        return this;
      }
      /**
       * <code>required bytes msg = 5;</code>
       */
      public Builder clearMsg() {
        copyOnWrite();
        instance.clearMsg();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GTransfer)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new protobuf.generate.internal.Internal.GTransfer();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasDest()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasUserId()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasPtoNum()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasMsg()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          protobuf.generate.internal.Internal.GTransfer other = (protobuf.generate.internal.Internal.GTransfer) arg1;
          dest_ = visitor.visitInt(hasDest(), dest_,
              other.hasDest(), other.dest_);
          netId_ = visitor.visitLong(
              hasNetId(), netId_,
              other.hasNetId(), other.netId_);
          userId_ = visitor.visitString(
              hasUserId(), userId_,
              other.hasUserId(), other.userId_);
          ptoNum_ = visitor.visitInt(
              hasPtoNum(), ptoNum_,
              other.hasPtoNum(), other.ptoNum_);
          msg_ = visitor.visitByteString(
              hasMsg(), msg_,
              other.hasMsg(), other.msg_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();
                  protobuf.generate.internal.Internal.Dest value = protobuf.generate.internal.Internal.Dest.forNumber(rawValue);
                  if (value == null) {
                    super.mergeVarintField(1, rawValue);
                  } else {
                    bitField0_ |= 0x00000001;
                    dest_ = rawValue;
                  }
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  netId_ = input.readUInt64();
                  break;
                }
                case 26: {
                  String s = input.readString();
                  bitField0_ |= 0x00000004;
                  userId_ = s;
                  break;
                }
                case 32: {
                  bitField0_ |= 0x00000008;
                  ptoNum_ = input.readUInt32();
                  break;
                }
                case 42: {
                  bitField0_ |= 0x00000010;
                  msg_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (protobuf.generate.internal.Internal.GTransfer.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:GTransfer)
    private static final protobuf.generate.internal.Internal.GTransfer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GTransfer();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static protobuf.generate.internal.Internal.GTransfer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<GTransfer> PARSER;

    public static com.google.protobuf.Parser<GTransfer> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GreetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Greet)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .Greet.From from = 1;</code>
     */
    boolean hasFrom();
    /**
     * <code>required .Greet.From from = 1;</code>
     */
    protobuf.generate.internal.Internal.Greet.From getFrom();
  }
  /**
   * <pre>
   *服务间建立连接时发送的协议
   * </pre>
   *
   * Protobuf type {@code Greet}
   */
  public  static final class Greet extends
      com.google.protobuf.GeneratedMessageLite<
          Greet, Greet.Builder> implements
      // @@protoc_insertion_point(message_implements:Greet)
      GreetOrBuilder {
    private Greet() {
      from_ = 1;
    }
    /**
     * Protobuf enum {@code Greet.From}
     */
    public enum From
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>Logic = 1;</code>
       */
      Logic(1),
      /**
       * <code>Gate = 2;</code>
       */
      Gate(2),
      /**
       * <code>Auth = 3;</code>
       */
      Auth(3),
      ;

      /**
       * <code>Logic = 1;</code>
       */
      public static final int Logic_VALUE = 1;
      /**
       * <code>Gate = 2;</code>
       */
      public static final int Gate_VALUE = 2;
      /**
       * <code>Auth = 3;</code>
       */
      public static final int Auth_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static From valueOf(int value) {
        return forNumber(value);
      }

      public static From forNumber(int value) {
        switch (value) {
          case 1: return Logic;
          case 2: return Gate;
          case 3: return Auth;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<From>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          From> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<From>() {
              public From findValueByNumber(int number) {
                return From.forNumber(number);
              }
            };

      private final int value;

      private From(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Greet.From)
    }

    private int bitField0_;
    public static final int FROM_FIELD_NUMBER = 1;
    private int from_;
    /**
     * <code>required .Greet.From from = 1;</code>
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Greet.From from = 1;</code>
     */
    public protobuf.generate.internal.Internal.Greet.From getFrom() {
      protobuf.generate.internal.Internal.Greet.From result = protobuf.generate.internal.Internal.Greet.From.forNumber(from_);
      return result == null ? protobuf.generate.internal.Internal.Greet.From.Logic : result;
    }
    /**
     * <code>required .Greet.From from = 1;</code>
     */
    private void setFrom(protobuf.generate.internal.Internal.Greet.From value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      from_ = value.getNumber();
    }
    /**
     * <code>required .Greet.From from = 1;</code>
     */
    private void clearFrom() {
      bitField0_ = (bitField0_ & ~0x00000001);
      from_ = 1;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, from_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, from_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static protobuf.generate.internal.Internal.Greet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static protobuf.generate.internal.Internal.Greet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static protobuf.generate.internal.Internal.Greet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static protobuf.generate.internal.Internal.Greet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static protobuf.generate.internal.Internal.Greet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.internal.Internal.Greet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static protobuf.generate.internal.Internal.Greet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.internal.Internal.Greet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static protobuf.generate.internal.Internal.Greet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static protobuf.generate.internal.Internal.Greet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.generate.internal.Internal.Greet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *服务间建立连接时发送的协议
     * </pre>
     *
     * Protobuf type {@code Greet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          protobuf.generate.internal.Internal.Greet, Builder> implements
        // @@protoc_insertion_point(builder_implements:Greet)
        protobuf.generate.internal.Internal.GreetOrBuilder {
      // Construct using protobuf.generate.internal.Internal.Greet.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required .Greet.From from = 1;</code>
       */
      public boolean hasFrom() {
        return instance.hasFrom();
      }
      /**
       * <code>required .Greet.From from = 1;</code>
       */
      public protobuf.generate.internal.Internal.Greet.From getFrom() {
        return instance.getFrom();
      }
      /**
       * <code>required .Greet.From from = 1;</code>
       */
      public Builder setFrom(protobuf.generate.internal.Internal.Greet.From value) {
        copyOnWrite();
        instance.setFrom(value);
        return this;
      }
      /**
       * <code>required .Greet.From from = 1;</code>
       */
      public Builder clearFrom() {
        copyOnWrite();
        instance.clearFrom();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Greet)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new protobuf.generate.internal.Internal.Greet();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasFrom()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          protobuf.generate.internal.Internal.Greet other = (protobuf.generate.internal.Internal.Greet) arg1;
          from_ = visitor.visitInt(hasFrom(), from_,
              other.hasFrom(), other.from_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();
                  protobuf.generate.internal.Internal.Greet.From value = protobuf.generate.internal.Internal.Greet.From.forNumber(rawValue);
                  if (value == null) {
                    super.mergeVarintField(1, rawValue);
                  } else {
                    bitField0_ |= 0x00000001;
                    from_ = rawValue;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (protobuf.generate.internal.Internal.Greet.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Greet)
    private static final protobuf.generate.internal.Internal.Greet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Greet();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static protobuf.generate.internal.Internal.Greet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Greet> PARSER;

    public static com.google.protobuf.Parser<Greet> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
